# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Malvika Sharan"
email: "malvikasharan@gmail.com"
description: "Computational Biology, Community Building, Open Science"
baseurl: ""
url: "https://malvikasharan.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Organizer Info
organizerName: "Malvika Sharan"
organizerAlternateName: ""
organizerDescription: "Computational Biology, Community Building, Open Science"
organizerEmail: "malvikasharan@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://malvikasharan.github.io/"

# Head
metaKeywords: "community, biology, science, bioinformatics, open source, events, diversity, inclusion"
twitterAccount: "@malvikasharan"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
#c4pUrl: "https://bit.ly/dfua-c4p"
#c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/publications/", text: "Publications"}
 - {permalink: "/projects/", text: "Community Projects"}
 - {link: "https://malvikasharan.github.io/surrounded-by-giants", text: "Blog"}
 - {link: "mailto:malvikasharan@gmail.com", text: "Contact"}

 #- {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {permalink: "/bio/", text: "Bio"}
rightNavigationButtons:
 - {permalink: "/bio/", text: "Bio"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Malvika Sharan"
eventDate: "Computational Biology, Community Building, Open Science"
typeoutTextValues: '"", "Community Builder", "Computational Biologist", "Open Scientist", "Collaborator"'
typeoutFallback: "Community Builder"
heroButtons:
 - {permalink: "/bio/", text: "Bio"}

# About Block
aboutTitle: "Overview"
aboutBlock:
 - {title: "Short Bio", image: "who.jpg", text: "", permalink: "/bio/"}
 - {title: "Current Projects", image: "why.jpg", text: "",  "/projects/"}
 - {title: "Topics of interest", image: "what.jpg", text: "",  "/blog/"}

# #Statistic Block
# statisticBlockImage: "statistic.jpg"
# statisticBlock:
#  - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
#  - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
#  - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
#  - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# #Latest News Block
# latestNewsTitle: "Latest news"

# #Venue Block
# venueBlockTitle: "Venue"
# venueBigImage: "venue_0.jpg"
# venueSmallImage1: "venue_1.jpg"
# venueSmallImage2: "venue_2.jpg"
# venueSmallImage3: "venue_3.jpg"
# venueTitle: "Kinopalace Cinema"
# venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# #Tweets Feed Block
# tweetsFeedImage: "twitter-feed.jpg"
# tweetsFeedTitle: "myfeed"
# twitterHashTag: "devfest"
# twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# #Partners Block
# organizersTitle: "Organizers"
# partnersTitle: "Partners"
# partnersC4sponsorsButton: "Become a sponsor"

footerBlocks:
 -
  title: "Social Links"
  links:
   - {link: "https://twitter.com/malvikasharan", text: "twitter", icon: "twitter"}
   - {link: "https://www.linkedin.com/in/malvikasharan/", text: "Linkedin"}
   - {link: "https://github.com/malvikasharan", text: "GitHub"}
 -
  title: "Current Affiliation"
  links:
   - {link: "https://www.embl.de/", text: "European Molecular Biology Laboratory (EMBL)"}
   - {link: "https://bio-it.embl.de", text: "EMBL Bio-IT"}
   - {link: "https://www.elixir-europe.org/about-us/who-we-are/nodes/germany", text: "ELIXIR Germany"}
 -
  title: "Other Involvements"
  links:
    - {link: "https://carpentries.org", text: "The Carpentries"}
    - {link: "https://foundation.mozilla.org/en/opportunity/mozilla-open-leaders/round-7/participants/participants---cohort-f/", text: "Mozilla Open Leaders"}


# #Team Block
# teamBlockTitle: "About us"
# aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."
